### ISSUE TITLE
Error record_linkage_example.py

### ISSUE THREAD

**Issue by asharma567** [datamade/dedupe-examples#24]
KeyError: 'Field type Price not valid. Valid types include Source, ShortString, Set, String, Interaction, Categorical, Text, Exact, LatLong, Custom'

**Comment by fgregg** [comment]
You need to updated dedupe.

**Comment by asharma567** [comment]
Thanks! that fixed it! also sent this to your other email..

*Hi Forest -- *

*Do you know if dedupe is capable of relating records based on match
percentage? i.e. return more than one match per record.*

*When I run csvlink it usually matches records one to one. Meaning I'll get
the number of matches equal to the number of the smaller record set.*

*eg*

*csvlink examples/linking_temp.csv examples/csv_example_messy_input.csv
--field_names Address Zip --output_file output.csv --skip_training*

*linking_temp.csv is 233 in line count *

*csv_example_messy_input is ~3000 in line count*
*matches output: 233*

*I'd imagine there are several other matches that come close to records, is
there any way to include these. Maybe get it to return a sorted list or
something.*

*Thanks!*
ᐧ

On Tue, Apr 28, 2015 at 1:52 PM, Forest Gregg <notifications@github.com>
wrote:

> You need to updated dedupe.
>
> On Tue, Apr 28, 2015 at 3:22 PM Ajay Sharma <notifications@github.com>
> wrote:
>
> > KeyError: 'Field type Price not valid. Valid types include Source,
> > ShortString, Set, String, Interaction, Categorical, Text, Exact, LatLong,
> > Custom'
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/datamade/dedupe-examples/issues/24>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/dedupe-examples/issues/24#issuecomment-97203766>
> .
>



-- 
Github <https://github.com/asharma567/> | LinkedIn
<http://www.linkedin.com/in/mrasharma/>

**Comment by fgregg** [comment]
The gazetteer class supports multiple matches.

**Comment by asharma567** [comment]
Will check it! if you have any good tutorials/examples in mind please let
me know...

ᐧ

On Tue, Apr 28, 2015 at 2:18 PM, Forest Gregg <notifications@github.com>
wrote:

> The gazetteer class supports multiple matches.
>
> On Tue, Apr 28, 2015 at 4:02 PM Ajay Sharma <notifications@github.com>
> wrote:
>
> > Thanks! that fixed it! also sent this to your other email..
> >
> > *Hi Forest -- *
> >
> > *Do you know if dedupe is capable of relating records based on match
> > percentage? i.e. return more than one match per record.*
> >
> > *When I run csvlink it usually matches records one to one. Meaning I'll
> get
> > the number of matches equal to the number of the smaller record set.*
> >
> > *eg*
> >
> > *csvlink examples/linking_temp.csv examples/csv_example_messy_input.csv
> > --field_names Address Zip --output_file output.csv --skip_training*
> >
> > *linking_temp.csv is 233 in line count *
> >
> > *csv_example_messy_input is ~3000 in line count*
> > *matches output: 233*
> >
> > *I'd imagine there are several other matches that come close to records,
> is
> > there any way to include these. Maybe get it to return a sorted list or
> > something.*
> >
> > *Thanks!*
> > ᐧ
> >
> > On Tue, Apr 28, 2015 at 1:52 PM, Forest Gregg <notifications@github.com>
> > wrote:
> >
> > > You need to updated dedupe.
> > >
> > > On Tue, Apr 28, 2015 at 3:22 PM Ajay Sharma <notifications@github.com>
> > > wrote:
> > >
> > > > KeyError: 'Field type Price not valid. Valid types include Source,
> > > > ShortString, Set, String, Interaction, Categorical, Text, Exact,
> > LatLong,
> > > > Custom'
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/datamade/dedupe-examples/issues/24>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/datamade/dedupe-examples/issues/24#issuecomment-97203766
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Github <https://github.com/asharma567/> | LinkedIn
> > <http://www.linkedin.com/in/mrasharma/>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/datamade/dedupe-examples/issues/24#issuecomment-97205880
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/dedupe-examples/issues/24#issuecomment-97209994>
> .
>



-- 
Github <https://github.com/asharma567/> | LinkedIn
<http://www.linkedin.com/in/mrasharma/>

**Comment by asharma567** [comment]
I tried using the address matching example with:

*clustered_dupes = linker.match(messy_addresses, threshold=0.4,
n_matches=4)*

and I haven't seen anything that gives me multiple matches per single
canonical record.

Just so I'm not burning days/hours trying to figure this out would you have
any examples of multiple matches?
ᐧ

On Tue, Apr 28, 2015 at 2:27 PM, Ajay Sharma <asharma567567@gmail.com>
wrote:

> Will check it! if you have any good tutorials/examples in mind please let
> me know...
>
> ᐧ
>
> On Tue, Apr 28, 2015 at 2:18 PM, Forest Gregg <notifications@github.com>
> wrote:
>
>> The gazetteer class supports multiple matches.
>>
>> On Tue, Apr 28, 2015 at 4:02 PM Ajay Sharma <notifications@github.com>
>> wrote:
>>
>> > Thanks! that fixed it! also sent this to your other email..
>> >
>> > *Hi Forest -- *
>> >
>> > *Do you know if dedupe is capable of relating records based on match
>> > percentage? i.e. return more than one match per record.*
>> >
>> > *When I run csvlink it usually matches records one to one. Meaning I'll
>> get
>> > the number of matches equal to the number of the smaller record set.*
>> >
>> > *eg*
>> >
>> > *csvlink examples/linking_temp.csv examples/csv_example_messy_input.csv
>> > --field_names Address Zip --output_file output.csv --skip_training*
>> >
>> > *linking_temp.csv is 233 in line count *
>> >
>> > *csv_example_messy_input is ~3000 in line count*
>> > *matches output: 233*
>> >
>> > *I'd imagine there are several other matches that come close to
>> records, is
>> > there any way to include these. Maybe get it to return a sorted list or
>> > something.*
>> >
>> > *Thanks!*
>> > ᐧ
>> >
>> > On Tue, Apr 28, 2015 at 1:52 PM, Forest Gregg <notifications@github.com
>> >
>> > wrote:
>> >
>> > > You need to updated dedupe.
>> > >
>> > > On Tue, Apr 28, 2015 at 3:22 PM Ajay Sharma <notifications@github.com
>> >
>> > > wrote:
>> > >
>> > > > KeyError: 'Field type Price not valid. Valid types include Source,
>> > > > ShortString, Set, String, Interaction, Categorical, Text, Exact,
>> > LatLong,
>> > > > Custom'
>> > > >
>> > > > —
>> > > > Reply to this email directly or view it on GitHub
>> > > > <https://github.com/datamade/dedupe-examples/issues/24>.
>> > > >
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> >
>> https://github.com/datamade/dedupe-examples/issues/24#issuecomment-97203766
>> > >
>> > > .
>> > >
>> >
>> >
>> >
>> > --
>> > Github <https://github.com/asharma567/> | LinkedIn
>> > <http://www.linkedin.com/in/mrasharma/>
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/datamade/dedupe-examples/issues/24#issuecomment-97205880
>> >
>>
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/datamade/dedupe-examples/issues/24#issuecomment-97209994>
>> .
>>
>
>
>
> --
> Github <https://github.com/asharma567/> | LinkedIn
> <http://www.linkedin.com/in/mrasharma/>
>



-- 
Github <https://github.com/asharma567/> | LinkedIn
<http://www.linkedin.com/in/mrasharma/>

**Comment by asharma567** [comment]
ᐧ

On Sat, May 2, 2015 at 10:30 AM, Ajay Sharma <asharma567567@gmail.com>
wrote:

> I tried using the address matching example with:
>
> *clustered_dupes = linker.match(messy_addresses, threshold=0.4,
> n_matches=4)*
>
> and I haven't seen anything that gives me multiple matches per single
> canonical record.
>
> Just so I'm not burning days/hours trying to figure this out would you
> have any examples of multiple matches?
> ᐧ
>
> On Tue, Apr 28, 2015 at 2:27 PM, Ajay Sharma <asharma567567@gmail.com>
> wrote:
>
>> Will check it! if you have any good tutorials/examples in mind please let
>> me know...
>>
>> ᐧ
>>
>> On Tue, Apr 28, 2015 at 2:18 PM, Forest Gregg <notifications@github.com>
>> wrote:
>>
>>> The gazetteer class supports multiple matches.
>>>
>>> On Tue, Apr 28, 2015 at 4:02 PM Ajay Sharma <notifications@github.com>
>>> wrote:
>>>
>>> > Thanks! that fixed it! also sent this to your other email..
>>> >
>>> > *Hi Forest -- *
>>> >
>>> > *Do you know if dedupe is capable of relating records based on match
>>> > percentage? i.e. return more than one match per record.*
>>> >
>>> > *When I run csvlink it usually matches records one to one. Meaning
>>> I'll get
>>> > the number of matches equal to the number of the smaller record set.*
>>> >
>>> > *eg*
>>> >
>>> > *csvlink examples/linking_temp.csv examples/csv_example_messy_input.csv
>>> > --field_names Address Zip --output_file output.csv --skip_training*
>>> >
>>> > *linking_temp.csv is 233 in line count *
>>> >
>>> > *csv_example_messy_input is ~3000 in line count*
>>> > *matches output: 233*
>>> >
>>> > *I'd imagine there are several other matches that come close to
>>> records, is
>>> > there any way to include these. Maybe get it to return a sorted list or
>>> > something.*
>>> >
>>> > *Thanks!*
>>> > ᐧ
>>> >
>>> > On Tue, Apr 28, 2015 at 1:52 PM, Forest Gregg <
>>> notifications@github.com>
>>> > wrote:
>>> >
>>> > > You need to updated dedupe.
>>> > >
>>> > > On Tue, Apr 28, 2015 at 3:22 PM Ajay Sharma <
>>> notifications@github.com>
>>> > > wrote:
>>> > >
>>> > > > KeyError: 'Field type Price not valid. Valid types include Source,
>>> > > > ShortString, Set, String, Interaction, Categorical, Text, Exact,
>>> > LatLong,
>>> > > > Custom'
>>> > > >
>>> > > > —
>>> > > > Reply to this email directly or view it on GitHub
>>> > > > <https://github.com/datamade/dedupe-examples/issues/24>.
>>> > > >
>>> > >
>>> > > —
>>> > > Reply to this email directly or view it on GitHub
>>> > > <
>>> >
>>> https://github.com/datamade/dedupe-examples/issues/24#issuecomment-97203766
>>> > >
>>> > > .
>>> > >
>>> >
>>> >
>>> >
>>> > --
>>> > Github <https://github.com/asharma567/> | LinkedIn
>>> > <http://www.linkedin.com/in/mrasharma/>
>>> >
>>> > —
>>> > Reply to this email directly or view it on GitHub
>>> > <
>>> https://github.com/datamade/dedupe-examples/issues/24#issuecomment-97205880
>>> >
>>>
>>> > .
>>> >
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/datamade/dedupe-examples/issues/24#issuecomment-97209994>
>>> .
>>>
>>
>>
>>
>> --
>> Github <https://github.com/asharma567/> | LinkedIn
>> <http://www.linkedin.com/in/mrasharma/>
>>
>
>
>
> --
> Github <https://github.com/asharma567/> | LinkedIn
> <http://www.linkedin.com/in/mrasharma/>
>



-- 
Github <https://github.com/asharma567/> | LinkedIn
<http://www.linkedin.com/in/mrasharma/>

**Comment by fgregg** [comment]
@asharma567 I'm not exactly sure what you mean. 

https://github.com/datamade/address-matching/blob/master/address_matching.py#L122-130 Is probably most relevant section of address-matching.py

Particularly, https://github.com/datamade/address-matching/blob/master/address_matching.py#L129

Notice, that unlike the other types of matching "cluster" consists of a set of possible matches. In this program we are just using the top scoring one (the first one).
