### ISSUE TITLE
What does WARNING:dedupe.training:Ran out of predicates mean?

### ISSUE THREAD

**Issue by Shotgunosine** [datamade/dedupe-examples#26]
I am attempting to train a deduper using data that has been manually clustered. I am just using a single field with the 'Name' type.

train_names is a 1500 item long dictionary with the form:
```
{'1': {'Cluster ID': '8061',
  'Id': '1',
  'name': 'ACME, LLC'},...
```
The code I am running for the training is:
```
fields = [
        {'field' : 'seller_name', 'type': 'Name'}
        ]
deduper = dedupe.Dedupe(fields)

deduper.markPairs(dedupe.trainingDataDedupe(train_names,'Cluster ID'))

deduper.train()
```

After running ```dedupe.train()``` I get the following error:
```WARNING:dedupe.training:Ran out of predicates```

What does this warning mean and do I need to do anything to remedy it, or can I carry on despite it?

**Comment by Shotgunosine** [comment]
Sorry, this should obviously be in dedupe, not dedupe-examples, moving it there.

**Comment by jve2kor** [comment]
Hello ,

Did you  find solution the above query?
currently even i am trying to use the labeled data to feed into dedupe for learning.
But having hard time.

Regards,
venkate
