### ISSUE TITLE
Unable to run csv_example

### ISSUE THREAD

**Issue by fschwahn** [datamade/dedupe-examples#28]
Hi,
first of all I'm sorry, I'm not really familiar with python or numpy, so this is probably a stupid mistake on my part, however I followed the installation instructions and could not run the csv_example. When I run it, I get the following error:
```
➜  csv_example git:(master) ✗ python csv_example.py
/Library/Python/2.7/site-packages/dedupe/backport.py:17: UserWarning: NumPy linked against 'Accelerate.framework'. Multiprocessing will be disabled. http://mail.scipy.org/pipermail/numpy-discussion/2012-August/063589.html
  warnings.warn("NumPy linked against 'Accelerate.framework'. "
importing data ...
csv_example.py:62: RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing an encoded string will likely have unexpected results.
  column = unidecode.unidecode(column)
starting active labeling...
Traceback (most recent call last):
  File "csv_example.py", line 133, in <module>
    dedupe.consoleLabel(deduper)
  File "/Library/Python/2.7/site-packages/dedupe/convenience.py", line 24, in consoleLabel
    uncertain_pairs = deduper.uncertainPairs()
  File "/Library/Python/2.7/site-packages/dedupe/api.py", line 757, in uncertainPairs
    self._trainClassifier()
  File "/Library/Python/2.7/site-packages/dedupe/api.py", line 683, in _trainClassifier
    self.classifier.fit(examples, labels)
  File "/Library/Python/2.7/site-packages/rlr/lr.py", line 17, in fit
    self.cv)
  File "/Library/Python/2.7/site-packages/rlr/crossvalidation.py", line 46, in gridSearch
    kFolds(labeled_examples, k)]
  File "/Library/Python/2.7/site-packages/rlr/crossvalidation.py", line 79, in kFolds
    labels[selected_indices])
IndexError: unsupported iterator index
```

I use OSX 10.10.5, and the preinstalled python (version Python 2.7.10). Also, have dedupe 1.2.2 installed, as well as numpy 1.10.1 .

Thanks for your help.

**Comment by fgregg** [comment]
Thanks. l'll try to replicate.

**Comment by cathydeng** [comment]
I was unable to replicate this - csv_example worked as expected

I have OSX 10.10.3, python 2.7.6, dedupe 1.2.2 & numpy 1.10.1

**Comment by fschwahn** [comment]
Thanks for looking into this, I'm stumped. I don't know what I've done wrong, it was just basically

```sh
sudo pip install dedupe
sudo pip install unidecode
```

and afterwards I cloned this repo and tried the example. Could it be related to any other dependency (e.g. `rlr`, I'm using version 2.1)?

**Comment by fgregg** [comment]
That's the same version I have.

**Comment by HZZeng** [comment]
I am using Windows. I found there were some unseen or special characters in the csv file. See whether there is still error after you remove those characters.

**Comment by mbauman** [comment]
Just a note for posterity — I ran into this and the issue for me was an old version of `numpy` (1.8) that didn't support the `selected_indices` range from the future.  Updating numpy solved the issue.
