### ISSUE TITLE
Ipython notebook

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-examples#32]
Hi @rebeccabilbro, 

Saw your IPython notebook fork. It looks really cool! Let me know if we can help.

**Comment by rebeccabilbro** [comment]
@fgregg Awesome! I coordinate a data science research lab together with @bbengfort and @bahadasx for @DistrictDataLabs. Our topic this Spring is entity resolution, and the group is very interested in `dedupe`! Would you be open to having a brief video conference with us sometime next week? We'd love to hear your thoughts and ideas (and any wishlist items!) you have for the project. Are you guys going to PyCon by any chance?

**Comment by fgregg** [comment]
Sounds cool, why don't we move this over to email. fgregg@datamade.us
