### ISSUE TITLE
pgsql_big_dedupe_example.py  issue

### ISSUE THREAD

**Issue by clementcarrier** [datamade/dedupe-examples#36]
Thanks for your last answer !

I got a new error message when i compiled the pgsql_big_dedupe_example.py file.After the active learning step and the cross validation for \alpha, I obtained : 

INFO:dedupe.blocking:Canopy: TfidfNGramCanopyPredicate: (0.8, name)
INFO:dedupe.training:Final predicate set:
INFO:dedupe.training:(SimplePredicate: (firstIntegerPredicate, name), SimplePredicate: (sameSevenCharStartPredicate, name))
INFO:dedupe.training:(SimplePredicate: (sameSevenCharStartPredicate, city), SimplePredicate: (twoGramFingerprint, name))
INFO:dedupe.training:(SimplePredicate: (commonIntegerPredicate, name), TfidfTextCanopyPredicate: (0.4, name))
INFO:dedupe.training:(SimplePredicate: (firstIntegerPredicate, address), TfidfTextCanopyPredicate: (0.6, address))
INFO:dedupe.training:(SimplePredicate: (commonTwoTokens, city), SimplePredicate: (firstIntegerPredicate, address))
Traceback (most recent call last):
  File "pgsql_big_dedupe_example.py", line 163, in <module>
    deduper.writeSettings(sf)
  File "/Applications/anaconda/lib/python3.5/site-packages/dedupe/api.py", line 142, in writeSettings
    pickle.dump(self.data_model, file_obj)
TypeError: write() argument must be str, not bytes

**Comment by fgregg** [comment]
Thanks, closed by https://github.com/datamade/dedupe-examples/commit/d6779f8308ece736cc5c60c7aa79ed4a8f03ddc7
