### ISSUE TITLE
New issue : big deduce example 

### ISSUE THREAD

**Issue by clementcarrier** [datamade/dedupe-examples#37]
New error message on file pgsql_big_dedupe_example.py : 

INFO:dedupe.blocking:Canopy: TfidfNGramCanopyPredicate: (0.8, address)
writing blocking map
Traceback (most recent call last):
  File "pgsql_big_dedupe_example.py", line 204, in <module>
    csv_writer.writerows(b_data)
  File "/Applications/anaconda/lib/python3.5/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'

**Comment by fgregg** [comment]
hmmm... it looks like there's a bunch of stuff in that example that are not
python3 compliant. If you want to make a PR, that's be great but I don't
have time to track them all down right now.

**Comment by clementcarrier** [comment]
I tried to use python2, but I had an issue with psycopg2..
I'll try to find the error, but I'm not a python expert!

Thanks for your answers

**Comment by fgregg** [comment]
I know the mysql example works with python3 if you want to try that.
